training:
  batch_size: 128
  n_epochs: 3000
  n_iters: 160000
  algo: "ssm"

data:
  dataset: "CELEBA"
  image_size: 64
  channels: 3

model:
  n_particles: 1
  # z_dim: 32
  eps_dim: 32
  z_dim: 64
  nef: 64
  ndf: 64
  fix_ssm: False
  deep_ssm: False
  origin_ssm: True
  fix_dec: False


optim:
  weight_decay: 0.0
  ssm_w_decay: 0.0
  optimizer: "Adam"
  lr: 0.005
